import ComponentWrapper from "@/layouts/ComponentWrapper";
import "@/styles/globals.css";
import type { Metadata } from "next";
import { Roboto_Mono } from "next/font/google";

const robotoMono = Roboto_Mono({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Form Builder",
  description: "Generated by Tuyen Tran",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={robotoMono.className}>
        <ComponentWrapper>{children}</ComponentWrapper>
      </body>
    </html>
  );
}
